language: ruby
cache: bundler

rvm:
  - 2.0.0
  - 2.1.5

before_install:
  - gem update bundler
  - gem install gisbn

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - eftakhairul@gmail.com
    on_failure: change
    on_success: never