language: ruby
cache: bundler

rvm:
  - jruby
  - 2.0.0

before_install:
  - gem update bundler
  - gem install gisbn

script:
  - bundle exec rake spec

notifications:
  email:
    recipients:
      - eftakhairul@gmail.com
    on_failure: change
    on_success: never