language: ruby

rvm:  
  - 2.5
  - 2.6

before_install:
  - gem install bundler
  - gem update bundler
  - gem install gisbn

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - eftakhairul@gmail.com
    on_failure: change
    on_success: never
